In [1]:
#!pip install numpy

In [2]:
#!pip install pandas

In [28]:
from requests import get
from bs4 import BeautifulSoup
import pandas as pd
numbers=[]
# Lists to store the scraped data in
titles = []
genres = []
directors = []
actors = []
plots = []
for i in range(51,2000,50):
    numbers.append(str(i))
for num in numbers:
    url = "https://www.imdb.com/search/title/?genres=romance&start="+num+"&explore=title_type,genres&ref_=adv_nxt"
    response = get(url)
    html_soup = BeautifulSoup(response.text, 'html.parser')
    movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
    print(type(movie_containers))
    print(len(movie_containers))
    
    # Extract data from individual movie container
    for container in movie_containers:
        if container.find('div', class_ = 'ratings-metascore') is not None:
            title = container.h3.a.text
            titles.append(title)
            genre = container.find('div',attrs={"class":"lister-item-content"}).find('p').find('span', attrs={"class":"genre"}).text
            genres.append(str.lstrip(genre))
            director = container.find('div',attrs={"class":"lister-item-content"}).find('p',attrs={"class":""}).find('a').text
            directors.append(director)
            actor = container.find('div',attrs={"class":"lister-item-content"}).find('p',attrs={"class":""}).find_all('a')
            actor.pop(0)
            for j in range(len(actor)): 
                actor[j]= (actor[j].get_text())
            actors.append(actor)
            plot =  container.find('div',attrs={"class":"lister-item-content"}).find_all('p',attrs={"class":"text-muted"})[1].text
            plots.append(str.lstrip(plot))

movies_df = pd.DataFrame({'Title': titles,
'Genre': genres,
'Director': directors,
'Actors': actors,
'Plot': plots
})
movies_df["Genre"]
print(movies_df.info())
movies_df.head(10)

<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'bs4.element.ResultSet'>
50
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1226 entries, 0 to 1225
Data columns (total 5 columns):
Title       1226 non-null object
Genre       1226 non-null object
Director    1226 non-null object
Actors      1226 non-null object
Plot        1226 non-null object
dtypes: object(5)
memory usage: 48.0+ KB
None

,Title,Genre,Director,Actors,Plot
0,Call Me by Your Name,"Drama, Romance",Luca Guadagnino,"[Armie Hammer, Timothée Chalamet, Michael Stuh...","In 1980s Italy, romance blossoms between a sev..."
1,Aladdin,"Adventure, Family, Fantasy",Guy Ritchie,"[Will Smith, Mena Massoud, Naomi Scott, Marwan...",A kind-hearted street urchin and a power-hungr...
2,The Princess Bride,"Adventure, Family, Fantasy",Rob Reiner,"[Cary Elwes, Mandy Patinkin, Robin Wright, Chr...","While home sick in bed, a young boy's grandfat..."
3,The 40 Year Old Virgin,"Comedy, Romance",Judd Apatow,"[Steve Carell, Catherine Keener, Paul Rudd, Ro...","Goaded by his buddies, a nerdy guy who's never..."
4,After,"Drama, Romance",Jenny Gage,"[Josephine Langford, Hero Fiennes Tiffin, Khad...",A young woman falls for a guy with a dark secr...
5,Grease,"Musical, Romance",Randal Kleiser,"[John Travolta, Olivia Newton-John, Stockard C...",Good girl Sandy Olsson (Olivia Newton-John) an...
6,Portrait de la jeune fille en feu,"Drama, Romance",Céline Sciamma,"[Noémie Merlant, Adèle Haenel, Luàna Bajrami, ...",On an isolated island in Brittany at the end o...
7,The Shape of Water,"Adventure, Drama, Fantasy",Guillermo del Toro,"[Sally Hawkins, Octavia Spencer, Michael Shann...",At a top secret research facility in the 1960s...
8,Fifty Shades of Grey,"Drama, Romance, Thriller",Sam Taylor-Johnson,"[Dakota Johnson, Jamie Dornan, Jennifer Ehle, ...",Literature student Anastasia Steele's life cha...
9,Mamma Mia! Here We Go Again,"Comedy, Musical, Romance",Ol Parker,"[Lily James, Amanda Seyfried, Meryl Streep, Cher]",Five years after the events of Mamma Mia! (200...

In [4]:
pages = [str(i) for i in range(1,5)]
years_url = [str(i) for i in range(2003,2020)]
from time import sleep
from random import randint
print(pages)

['1', '2', '3', '4']

In [5]:
from IPython.core.display import clear_output
from time import time
start_time = time()
requests = 0
for _ in range(5):
# A request would go here
    requests += 1
    sleep(randint(1,3))
    current_time = time()
    elapsed_time = current_time - start_time
    print('Request: {}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
clear_output(wait = True)

Request: 1; Frequency: 0.3332768641889532 requests/s
Request: 2; Frequency: 0.33326394148455546 requests/s
Request: 3; Frequency: 0.374815186343847 requests/s
Request: 4; Frequency: 0.4441043843896976 requests/s
Request: 5; Frequency: 0.4541952787689493 requests/s

In [6]:
from warnings import warn
warn("Warning Simulation")

C:\Users\Tanya\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Warning Simulation

In [14]:
# Redeclaring the lists to store data in
titles = []
genres = []
directors = []
actors = []
plots = []
#headers = {"Accept-Language": "en-US, en;q=0.5"}
# Preparing the monitoring of the loop
start_time = time()
requests = 0
numbers=[]
for i in range(51,2000,50):
    numbers.append(str(i))
    

# For every year in the interval 2000-2020
for num in numbers:

    # For every page in the interval 1-4
    for page in pages:

        # Make a get request
        response = get('https://www.imdb.com/search/title/?genres=comedy&start='+num+'&explore=title_type,genres&ref_=adv_nxt')

        # Pause the loop
        sleep(randint(8,15))

        # Monitor the requests
        requests += 1
        elapsed_time = time() - start_time
        print('Request:{}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
        clear_output(wait = True)

        # Throw a warning for non-200 status codes
        if response.status_code != 200:
            warn('Request: {}; Status code: {}'.format(requests, response.status_code))

        # Break the loop if the number of requests is greater than expected
        if requests > 50:
            warn('Number of requests was greater than expected.')
            break

        # Parse the content of the request with BeautifulSoup
        page_html = BeautifulSoup(response.text, 'html.parser')

        # Select all the 50 movie containers from a single page
        mv_containers = page_html.find_all('div', class_ = 'lister-item mode-advanced')

        # For every movie of these 50
        for container in movie_containers:
            if container.find('div', class_ = 'ratings-metascore') is not None:
                title = container.h3.a.text
                titles.append(title)
                genre = container.find('div',attrs={"class":"lister-item-content"}).find('p').find('span', attrs={"class":"genre"}).text
                genre=str.rstrip(genre)
                genres.append(str.lstrip(genre))
                director = container.find('div',attrs={"class":"lister-item-content"}).find('p',attrs={"class":""}).find('a').text
                directors.append(director)
                actor = container.find('div',attrs={"class":"lister-item-content"}).find('p',attrs={"class":""}).find_all('a')
                actor.pop(0)
                for j in range(len(actor)): 
                    actor[j]= (actor[j].get_text())
                actors.append(actor)
                plot =  container.find('div',attrs={"class":"lister-item-content"}).find_all('p',attrs={"class":"text-muted"})[1].text
                plots.append(str.lstrip(plot))

Request:77; Frequency: 0.07213626656102284 requests/s

In [16]:
movies_df = pd.DataFrame({'Title': titles,
'Genre': genres,
'Director': directors,
'Actors': actors,
'Plot': plots
})
movies_df["Genre"]
print(movies_df.info())
movies_df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 5 columns):
Title       1200 non-null object
Genre       1200 non-null object
Director    1200 non-null object
Actors      1200 non-null object
Plot        1200 non-null object
dtypes: object(5)
memory usage: 47.0+ KB
None

,Title,Genre,Director,Actors,Plot
0,Extraction,"Action, Thriller",Sam Hargrave,"[Chris Hemsworth, Bryon Lerum, Ryder Lerum, Ru...","Tyler Rake, a fearless black market mercenary,..."
1,Birds of Prey: And the Fantabulous Emancipatio...,"Action, Adventure, Crime",Cathy Yan,"[Margot Robbie, Rosie Perez, Mary Elizabeth Wi...","After splitting with the Joker, Harley Quinn j..."
2,The Invisible Man,"Horror, Mystery, Sci-Fi",Leigh Whannell,"[Elisabeth Moss, Oliver Jackson-Cohen, Harriet...",When Cecilia's abusive ex takes his own life a...
3,Bad Boys for Life,"Action, Comedy, Crime",Adil El Arbi,"[Bilall Fallah, Will Smith, Martin Lawrence, V...",Miami detectives Mike Lowrey and Marcus Burnet...
4,Onward,"Animation, Adventure, Comedy",Dan Scanlon,"[Tom Holland, Chris Pratt, Julia Louis-Dreyfus...",Two elven brothers embark on a quest to bring ...
5,Sonic the Hedgehog,"Action, Adventure, Comedy",Jeff Fowler,"[Ben Schwartz, James Marsden, Jim Carrey, Tika...","After discovering a small, blue, fast hedgehog..."
6,Spenser Confidential,"Action, Comedy, Crime",Peter Berg,"[Mark Wahlberg, Winston Duke, Alan Arkin, Iliz...","When two Boston police officers are murdered, ..."
7,The Old Guard,"Action, Adventure, Fantasy",Gina Prince-Bythewood,"[Charlize Theron, KiKi Layne, Matthias Schoena...",A covert team of immortal mercenaries are sudd...
8,Eurovision Song Contest: The Story of Fire Saga,"Comedy, Music",David Dobkin,"[Will Ferrell, Rachel McAdams, Dan Stevens, Mi...",When aspiring musicians Lars and Sigrit are gi...
9,The Hunt,"Action, Horror, Thriller",Craig Zobel,"[Betty Gilpin, Hilary Swank, Ike Barinholtz, W...",Twelve strangers wake up in a clearing. They d...

In [12]:
numbers=[]
for i in range(51,2000,50):
    numbers.append(str(i))

In [31]:
rom=pd.read_csv('romance-movie-database.csv')
mys=pd.read_csv('mystery-movie-database.csv')
com=pd.read_csv('comedy-movie-database.csv')

In [53]:
vertical_stack = pd.concat([mys,rom,com], axis=0)
vertical_stack = vertical_stack[['Title','Genre','Director','Actors','Plot']]
#vertical_stack.drop([Unnamed], axis=1)
vertical_stack=vertical_stack.reset_index(drop=True)

In [54]:
print(vertical_stack)

                                       Title  \
0                                   Ad Astra
1                                 Hereditary
2                                   The Firm
3                               Ready or Not
4                            Double Jeopardy
...                                      ...
3322                           Harlem Nights
3323                                    Goon
3324                        Oliver & Company
3325   Legally Blonde 2: Red, White & Blonde
3326  Romy and Michele's High School Reunion

                                         Genre                 Director  \
0        Adventure, Drama, Mystery                           James Gray
1           Drama, Horror, Mystery                            Ari Aster
2         Drama, Mystery, Thriller                       Sydney Pollack
3          Comedy, Horror, Mystery                Matt Bettinelli-Olpin
4            Crime, Drama, Mystery                      Bruce Beresford
...                                        ...                      ...
3322          Comedy, Crime, Drama                         Eddie Murphy
3323          Comedy, Drama, Sport                        Michael Dowse
3324  Animation, Adventure, Comedy                      George Scribner
3325                        Comedy              Charles Herman-Wurmfeld
3326                        Comedy                         David Mirkin

                                                 Actors  \
0     ['Brad Pitt', 'Tommy Lee Jones', 'Ruth Negga',...
1     ['Toni Collette', 'Milly Shapiro', 'Gabriel By...
2     ['Tom Cruise', 'Jeanne Tripplehorn', 'Gene Hac...
3     ['Tyler Gillett', 'Samara Weaving', 'Adam Brod...
4     ['Ashley Judd', 'Tommy Lee Jones', 'Bruce Gree...
...                                                 ...
3322  ['Eddie Murphy', 'Richard Pryor', 'Redd Foxx',...
3323  ['Seann William Scott', 'Jay Baruchel', 'Aliso...
3324  ['Joey Lawrence', 'Billy Joel', 'Cheech Marin'...
3325  ['Reese Witherspoon', 'Sally Field', 'Bob Newh...
3326  ['Mira Sorvino', 'Lisa Kudrow', 'Janeane Garof...

                                                   Plot
0     Astronaut Roy McBride undertakes a mission acr...
1     A grieving family is haunted by tragic and dis...
2     A young lawyer joins a prestigious law firm on...
3     A bride's wedding night takes a sinister turn ...
4     A woman framed for her husband's murder suspec...
...                                                 ...
3322  During the 1930s, a New York City illegal gamb...
3323  Labeled an outcast by his brainy family, a bou...
3324  A lost and alone kitten joins a gang of dogs e...
3325  Elle Woods heads to Washington, D.C. to join t...
3326  Two dim-witted, inseparable friends hit the ro...

[3327 rows x 5 columns]

In [55]:
vertical_stack.to_csv('final-movie-database.csv')